import{a as v,S as P,i}from"./assets/vendor-CrlV4O_2.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const q="50394880-18f1d62e7610047a874f2c643",S="https://pixabay.com/api/";async function m(o,s){const e={key:q,q:o,page:s,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await v.get(S,{params:e})).data}const p=document.querySelector(".gallery"),h=document.querySelector(".loader"),g=document.querySelector(".load-more"),M=new P(".gallery a");function y(o){const s=o.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",s),M.refresh()}function R(){p.innerHTML=""}function L(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}function w(){g.classList.remove("hidden")}function l(){g.classList.add("hidden")}const f=document.querySelector(".form"),B=document.querySelector(".load-more");let c="",a=1,u=0;f.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),!c){i.warning({message:"Please enter a search query",position:"topRight"});return}a=1,R(),l(),L();try{const e=await m(c,a);if(u=e.totalHits,e.hits.length===0){i.info({message:"No images found",position:"topRight"});return}y(e.hits);const n=e.hits.length,t=Math.ceil(u/n);a<t?w():l()}catch{i.error({message:"Failed to fetch images",position:"topRight"})}finally{b(),f.reset()}});B.addEventListener("click",async()=>{a+=1,L(),l();try{const o=await m(c,a);y(o.hits);const s=o.hits.length,e=Math.ceil(u/s);a<e?w():(i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l());const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}catch{i.error({message:"Error loading more images",position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
